apiVersion: v1
kind: Service
metadata:
  name: mywebhook-svc
  namespace: xiong
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    mywebhook: "true"
  sessionAffinity: None
  type: ClusterIP